{"name": "Проверяем принятие заказа c некорректным id курьера в запросе", "status": "passed", "start": 1723401131142, "stop": 1723401131411, "uuid": "786f1b19-2321-4602-87e0-f037f9cb7dac", "historyId": "a7ebd3c2b169856a57a68d1a29f27160", "testCaseId": "a7ebd3c2b169856a57a68d1a29f27160", "fullName": "tests.test_accept_order.TestAcceptOrder#test_accept_order_with_invalid_courier_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "zurujal-osx"}, {"name": "thread", "value": "1163-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}]}