{"name": "Проверка получения заказа по номеру с некорректным track id в запросе", "status": "passed", "start": 1723401134616, "stop": 1723401134710, "uuid": "22f93ed3-5969-4bc4-b9ef-e38efb98ea12", "historyId": "b3ba206b805dcc7717ed2d84d8918876", "testCaseId": "b3ba206b805dcc7717ed2d84d8918876", "fullName": "tests.test_receive_order_by_number.TestLoginCourier#test_get_order_with_invalid_track", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_receive_order_by_number"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "zurujal-osx"}, {"name": "thread", "value": "1163-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_receive_order_by_number"}]}